# Generated by Django 5.2.1 on 2025-05-12 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('position', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff_monitor.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSuperintendent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff_monitor.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('managed_staff', models.ManyToManyField(blank=True, related_name='supervisors', to='staff_monitor.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('punctuality', models.CharField(choices=[('4', 'Excellent/Outstanding'), ('3', 'Good/Satisfactory'), ('2', 'Average/Needs Improvement'), ('1', 'Poor/Unsatisfactory')], max_length=1)),
                ('appearance', models.CharField(choices=[('4', 'Excellent/Outstanding'), ('3', 'Good/Satisfactory'), ('2', 'Average/Needs Improvement'), ('1', 'Poor/Unsatisfactory')], max_length=1)),
                ('patient_attitude', models.CharField(choices=[('4', 'Excellent/Outstanding'), ('3', 'Good/Satisfactory'), ('2', 'Average/Needs Improvement'), ('1', 'Poor/Unsatisfactory')], max_length=1)),
                ('teamwork', models.CharField(choices=[('4', 'Excellent/Outstanding'), ('3', 'Good/Satisfactory'), ('2', 'Average/Needs Improvement'), ('1', 'Poor/Unsatisfactory')], max_length=1)),
                ('policy_adherence', models.CharField(choices=[('4', 'Excellent/Outstanding'), ('3', 'Good/Satisfactory'), ('2', 'Average/Needs Improvement'), ('1', 'Poor/Unsatisfactory')], max_length=1)),
                ('communication', models.CharField(choices=[('4', 'Excellent/Outstanding'), ('3', 'Good/Satisfactory'), ('2', 'Average/Needs Improvement'), ('1', 'Poor/Unsatisfactory')], max_length=1)),
                ('emergency_handling', models.CharField(choices=[('4', 'Excellent/Outstanding'), ('3', 'Good/Satisfactory'), ('2', 'Average/Needs Improvement'), ('1', 'Poor/Unsatisfactory')], max_length=1)),
                ('initiative', models.CharField(choices=[('4', 'Excellent/Outstanding'), ('3', 'Good/Satisfactory'), ('2', 'Average/Needs Improvement'), ('1', 'Poor/Unsatisfactory')], max_length=1)),
                ('integrity', models.CharField(choices=[('4', 'Excellent/Outstanding'), ('3', 'Good/Satisfactory'), ('2', 'Average/Needs Improvement'), ('1', 'Poor/Unsatisfactory')], max_length=1)),
                ('overall_performance', models.CharField(choices=[('4', 'Excellent/Outstanding'), ('3', 'Good/Satisfactory'), ('2', 'Average/Needs Improvement'), ('1', 'Poor/Unsatisfactory')], max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_monitor.staff')),
            ],
            options={
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
