# Generated by Django 5.2.1 on 2025-05-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='incident_photo',
            field=models.ImageField(blank=True, null=True, upload_to='incident_photos/'),
        ),
    ]
