# Generated by Django 5.2.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0002_incidentreport_incident_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereport',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_monitor.staff'),
        ),
        migrations.AddField(
            model_name='performancereport',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_reports', to='staff_monitor.departmenthead'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='staff_monitor.staff'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='staff_monitor.departmenthead'),
        ),
        migrations.AlterUniqueTogether(
            name='performancereport',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='performancereport',
            constraint=models.UniqueConstraint(condition=models.Q(('staff__isnull', False)), fields=('staff', 'date'), name='unique_staff_date'),
        ),
        migrations.AddConstraint(
            model_name='performancereport',
            constraint=models.UniqueConstraint(condition=models.Q(('department_head__isnull', False)), fields=('department_head', 'date'), name='unique_department_head_date'),
        ),
        migrations.AddConstraint(
            model_name='performancereport',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('department_head__isnull', True), ('staff__isnull', False)), models.Q(('department_head__isnull', False), ('staff__isnull', True)), _connector='OR'), name='only_staff_or_department_head'),
        ),
    ] 