# Generated by Django 5.2.1 on 2025-05-17 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0002_rename_medicalsuperintendent_departmenthead'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdepartments', to='staff_monitor.department')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'department')},
            },
        ),
    ]
