# Generated by Django 5.2.1 on 2025-05-17 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0003_subdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='designation',
            field=models.CharField(default='Department Head', max_length=100),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='subdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='staff_monitor.subdepartment'),
        ),
    ]
