# Generated by Django 5.2.1 on 2025-06-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0003_add_department_head_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='managed_subdepartments',
            field=models.ManyToManyField(blank=True, related_name='department_heads', to='staff_monitor.subdepartment'),
        ),
    ]
