# Generated by Django 4.2.4 on 2024-05-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0003_add_department_head_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='incident_photo',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_photo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_photo_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ] 