# Generated by Django 5.2.1 on 2025-05-17 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0004_departmenthead_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='subdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='staff_monitor.subdepartment'),
        ),
    ]
