# Generated by Django 5.2.1 on 2025-05-21 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0005_staff_appointment_date_staff_subdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='is_hr_head',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HRPrivileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_add_staff', models.BooleanField(default=False)),
                ('can_edit_staff', models.BooleanField(default=False)),
                ('can_delete_staff', models.BooleanField(default=False)),
                ('can_add_department_head', models.BooleanField(default=False)),
                ('can_edit_department_head', models.BooleanField(default=False)),
                ('can_delete_department_head', models.BooleanField(default=False)),
                ('can_manage_departments', models.BooleanField(default=False)),
                ('can_view_all_reports', models.BooleanField(default=False)),
                ('can_delete_reports', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hr_head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privileges', to='staff_monitor.departmenthead')),
            ],
            options={
                'verbose_name': 'HR Privileges',
                'verbose_name_plural': 'HR Privileges',
            },
        ),
    ]
