# Generated by Django 5.2.1 on 2025-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0005_staff_managed_by_staff_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='contact_info',
            field=models.CharField(blank=True, help_text="Staff member's contact information", max_length=200, null=True),
        ),
    ]
