# Generated by Django 5.2.1 on 2025-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0006_staff_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='status',
            field=models.CharField(choices=[('active', 'Currently Working'), ('on_leave', 'On Leave'), ('transferred', 'Transferred to Another Hospital'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='status_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the status (e.g., leave duration, transfer details)', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('active', 'Currently Working'), ('on_leave', 'On Leave'), ('transferred', 'Transferred to Another Hospital'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='status_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the status (e.g., leave duration, transfer details)', null=True),
        ),
    ]
