# Generated by Django 5.2.1 on 2025-05-21 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0006_add_hr_privileges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=20, unique=True)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('incident_location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident_type', models.CharField(max_length=255)),
                ('other_incident_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(verbose_name='Description of Incident')),
                ('individuals_involved', models.TextField(blank=True, verbose_name='Individuals Involved')),
                ('immediate_action', models.TextField(blank=True, verbose_name='Immediate Action Taken')),
                ('follow_up_action', models.TextField(blank=True, verbose_name='Follow-up Action')),
                ('witness_statement', models.TextField(blank=True)),
                ('patient_impact', models.TextField(blank=True)),
                ('reported_to_authority', models.BooleanField(default=False)),
                ('authority_report_date', models.DateField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='staff_monitor.staff')),
            ],
            options={
                'ordering': ['-incident_date', '-incident_time'],
            },
        ),
    ]
