# Generated by Django 5.2.1 on 2025-05-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0007_incidentreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncidentReport',
        ),
    ]
