# Generated by Django 5.2.1 on 2025-06-14 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0007_departmenthead_status_departmenthead_status_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmenthead',
            name='status_notes',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='status_notes',
        ),
        migrations.AddField(
            model_name='staff',
            name='contact_number',
            field=models.CharField(blank=True, help_text="Staff member's contact number", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_monitor.department'),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('left_service', 'Left Service')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='subdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_monitor.subdepartment'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('left_service', 'Left Service')], default='active', max_length=20),
        ),
    ]
