# Generated by Django 5.2.1 on 2025-05-26 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0008_delete_incidentreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, unique=True)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('incident_location', models.CharField(max_length=255)),
                ('incident_types', models.JSONField(default=list)),
                ('other_incident_type', models.CharField(blank=True, max_length=255, null=True)),
                ('related_parties', models.JSONField(default=list)),
                ('individuals_involved', models.TextField(blank=True)),
                ('incident_description', models.TextField()),
                ('contributing_factors', models.JSONField(default=list)),
                ('other_contributing_factor', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('immediate_action', models.TextField()),
                ('follow_up_actions', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='staff_monitor.staff')),
            ],
            options={
                'ordering': ['-incident_date', '-incident_time'],
            },
        ),
    ]
