# Generated by Django 5.2.1 on 2025-06-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0009_transfer_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='managed_by',
        ),
        migrations.AddField(
            model_name='staff',
            name='managed_by',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='staff_monitor.departmenthead'),
        ),
    ]
