# Generated by Django 5.2.1 on 2025-05-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0009_incidentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='contributing_factors',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_types',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='related_parties',
            field=models.TextField(default='[]'),
        ),
    ]
