# Generated by Django 5.2.1 on 2025-06-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0010_remove_staff_managed_by_staff_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='managed_departments',
            field=models.ManyToManyField(blank=True, help_text='Additional departments this head manages.', related_name='managing_heads', to='staff_monitor.department'),
        ),
    ]
