# Generated by Django 5.2.1 on 2025-05-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0010_add_incident_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='contributing_factors',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='incident_description',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='other_contributing_factor',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='severity',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='prepared_by',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='immediate_action',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='individuals_involved',
            field=models.TextField(default='[]'),
        ),
    ]
