# Generated by Django 5.2.1 on 2025-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0011_remove_incidentreport_contributing_factors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
