# Generated by Django 5.2.1 on 2025-06-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0011_departmenthead_managed_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='qualification',
            field=models.CharField(blank=True, help_text='Educational or professional qualifications', max_length=200, null=True),
        ),
    ]
