# Generated by Django 5.2.1 on 2025-06-23 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0012_departmenthead_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthead',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_monitor.department'),
        ),
        migrations.AlterField(
            model_name='departmenthead',
            name='managed_departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this head manages.', related_name='managing_heads', to='staff_monitor.department'),
        ),
    ]
