# Generated by Django 5.2.1 on 2025-06-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_monitor', '0013_alter_departmenthead_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenthead',
            name='managed_subdepartment_heads',
            field=models.ManyToManyField(blank=True, related_name='supervised_by', to='staff_monitor.departmenthead'),
        ),
    ]
