services:
  - type: web
    name: hospital-performance-monitor
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn performance_monitor.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hospital-performance-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "True"
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: hospital-performance-db
    databaseName: hospital_performance
    user: hospital_user 